// This file would normally be generated by TanStack Router build tooling.
// For this mock environment we manually compose the route tree.
import { Route as rootRoute } from './_layout';
import { Route as indexRoute } from './index';
import { Route as analyticsRoute } from './analytics';
import { Route as prDetailRoute } from './pr/$prId';

const routeTree = rootRoute.addChildren([indexRoute, analyticsRoute, prDetailRoute]);
export { routeTree };
