name: Commit Crab
on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: 'Choose which app to build'
        required: true
        default: 'Low Code Automation' # Set a default value here
        options: # Specify available options
          - Low Code Automation

      platform:
        type: choice
        description: 'Choose a platform to build for'
        required: true
        default: 'Windows (Latest)' # Set a default value here
        options:
          - Windows (Latest)
          - MacOS (Apple Silicon)
          - MacOS (Intel)

      env-choice:
        type: choice
        description: 'Choose the yarn run command'
        required: true
        default: 'Staging' # Set a default value here
        options:
          - Staging
          - Preprod
          - Production
          - Production-DR

run-name: SuperApp Build for ${{ inputs.platform }} - ${{ inputs.env-choice }}